name: CI/CD

on:
  push:
    branches:
      - main
      - release
  pull_request:

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        id: node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: |
          gulp bundle

      - name: Get branch name
        if: ${{ contains(github.ref, 'refs/heads/') }}
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      # very unelegant, but hoster does not support SSH key authentication :-/
      - name: Copy artifact to Webspace
        run: |
          sshpass -p ${{secrets.SSH_PASSWORD}} scp build/ui-bundle.zip ${{secrets.SSH_USERNAME}}@${{secrets.SSH_HOSTNAME}}:/var/www/web25462234/html/files.my-agrirouter.com/ui-bundle-${{ env.BRANCH_NAME }}.zip
